trigger:
  - none
parameters:
  - name: environment
    displayName: "Select Environment"
    type: string
    default: "dev"
    values:
      - dev
      - prd

variables:
  - template: ../variables/${{ parameters.environment }}-config.yml

stages:
  - stage: DeployInfrastructure
    displayName: "Deploy Infrastructure"
    jobs:
      - job: Deploy
        displayName: "Deploy Resources"
        pool:
          vmImage: "windows-latest"
        steps:
          - task: AzureKeyVault@2
            displayName: "Fetch Secrets from Key Vault"
            inputs:
              azureSubscription: "${{ variables.azureSubscription }}"
              KeyVaultName: "$(keyVaultName)"
              SecretsFilter: "sqlmi-admin-password"
              RunAsPreJob: false

          - task: AzurePowerShell@5
            displayName: "Deploy Bicep Template"
            inputs:
              azureSubscription: "${{ variables.azureSubscription }}"
              ScriptType: "InlineScript"
              Inline: |
                try {
                    # Set the subscription context
                    Set-AzContext -SubscriptionId "${{ variables.subscriptionID }}"

                    Write-Host "Starting Deployment..."

                    # Convert Key Vault password to SecureString
                    $adminPassword = ConvertTo-SecureString "$(sqlmi-admin-password)" -AsPlainText -Force

                    # Deploy Bicep template
                    $deployment = New-AzResourceGroupDeployment `
                      -ResourceGroupName "$(resourceGroupName)" `
                      -TemplateFile "bicep/main.bicep" `
                      -environment "$(environment)" `
                      -location "$(location)" `
                      -vnetAddressSpace "$(vnetAddressSpace)" `
                      -subnetAddressSpaceSQLMI "$(subnetAddressSpaceSQLMI)" `
                      -subnetAddressSpacePrivateEndpoint "$(subnetAddressSpacePrivateEndpoint)" `
                      -administratorPassword $adminPassword `
                      -adminObjectId "$(adminObjectId)" `
                      -tenantId "$(tenantId)" `
                      -Verbose

                    Write-Host "Deployment Completed Successfully!"
                }
                catch {
                    Write-Host "Deployment Failed!"
                    Write-Host "====================================="
                    Write-Host "Error Details:"
                    $_.Exception | Format-List -Force
                    Write-Host "====================================="
                    throw $_
                }
              azurePowerShellVersion: "LatestVersion"

